# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: greedying
email: greedying@163.com
description: > # this means to ignore newlines until "baseurl:"
    greedying的博客，包括但不限于技术
baseurl: "" # the subpath of your site, e.g. /blog
lang: "cn"
url: "http://greedying.com" # the base hostname & protocol for your site
twitter_username:
github_username:  greedying
disqus_username:
google_analytics:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
